# frontend/Dockerfile.prod
FROM node:20-alpine

WORKDIR /app

# Instala as dependências de forma limpa
COPY package.json package-lock.json* ./
RUN npm ci

# Copia o código e realiza o build de produção
COPY . .
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
RUN npm run build

# Comando para produção
CMD ["npm", "start"]