services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8000:8000" 
    volumes:
      - backend_data:/app/data
    env_file:
      - ./backend/.env
    environment:
      - DB_PATH=/app/data/triagem.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - NEXT_PUBLIC_API_URL=https://primeiroolhar.app.br
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://primeiroolhar.app.br
    depends_on:
      - backend

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

volumes:
  backend_data:
  npm_data:
  npm_letsencrypt: