server {
    listen 80;
    server_name primeiroolhar.app.br; 

    # Rota para o Frontend (Next.js)
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Rota para o Backend (FastAPI/Python)
    location /api/ {
        # O Nginx repassa tudo que chega em /api/ para o backend na porta 8000
        proxy_pass http://localhost:8000/; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Aumentar timeout para processamento de vídeo
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        client_max_body_size 50M; # Limite de tamanho do vídeo
    }
}